import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Suspense } from "react";
import Loading from "./loading";
import FormContainer from "@/components/FormContainer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col gap-12 items-center justify-center p-24">
          <FormContainer />
          {children}
          {/* <Suspense fallback={<Loading />}>{children}</Suspense> */}
        </div>
      </body>
    </html>
  );
}
